### ISSUE TITLE
Access to concord tool?

### ISSUE THREAD

**Issue by anirjoshi** [slebok/slebok.github.com#2]
Hello, from where can I get access to the [CONCORD](https://github.com/slebok/slebok.github.io/blob/master/proverb/concord.html) tool mentioned in this repo?

**Comment by Sophietje** [comment]
Hi! If there's no link on the page, that means that we weren't able to find a link to an artifact or a repository for the tool. I recommend reaching out to the authors of the paper ([Program Synthesis Using Deduction-Guided Reinforcement Learning](https://doi.org/10.1007/978-3-030-53291-8_30)) to ask them if it's available somewhere.
